install.packages("dslabs")
library(dslabs)
library(dplyr)
data("heights")
h<-heights$height
head(heights)
dim(heights)
?hist
plot(heights)
View(heights)
hist(females)
hist(males)
hist(males,freq = F, breaks = 30)
hist(females,freq=F, breaks = 30)
hist(males,freq = F, ylim = c(0,0.01), breaks = 25, las=1, main = "Female Heights")
hist(females,freq = F, ylim = c(0,0.01), breaks = 25, las=1, main = "Female Heights")
lines(density(females), col=2,lwd=3)
lines(density(males), col=2,lwd=3)
