#random variable exercises
library(downloader) 
url <- "https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/femaleControlsPopulation.csv"
filename <- basename(url)
download(url, destfile=filename)
x <- unlist( read.csv(filename) )
RNGkind("Mersenne-Twister", "Inversion", "Rejection")
dim(basename)
head(filename)
View(filename)
View(x)
##What is the average of these weights?
?mean
length(x)
class(x)
mean(x)
set.seed(1)
sample(x,5)
control<-sample(x, size=5)
mean(control)
nulldiff <- mean(x) - mean(control)
sum(mean(x)-mean(control))
?abs
abs(mean(x) - mean(control))
## what is absolute value of the difference between the average of the sample 
## And the average of all the values
mean(x)
mean(control)
abs(x)
abs(control)
mean(x)
mean(control)
sum(mean(control)-mean(x))
set.seed(5)    
sample(x,5)
control2<-sample(x, size = 5)
mean(control)
mean(control2)
mean(x)
mean(control2)-mean(x)
set.seed(1)
X <- sample(x,5)
abs( mean(X) - mean(x) )
set.seed(5)
X <- sample(x,5)
abs( mean(X) - mean(x) )
